// src/utils/mockData.ts
import { Product } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Nike Air Max 270',
    description: 'Les Nike Air Max 270 offrent un confort exceptionnel avec leur unité Air visible et leur design moderne.',
    price: 149.99,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500',
      'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=500',
    ],
    category: 'shoes',
    rating: 4.5,
    reviewsCount: 328,
    inStock: true,
    brand: 'Nike',
    sizes: ['39', '40', '41', '42', '43', '44'],
    colors: ['Noir', 'Blanc', 'Bleu'],
    tags: ['sport', 'running', 'lifestyle'],
  },
  {
    id: '2',
    name: 'iPhone 15 Pro',
    description: 'Le dernier iPhone avec puce A17 Pro, appareil photo 48MP et design en titane.',
    price: 1229.00,
    images: [
      'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500',
      'https://images.unsplash.com/photo-1696446702721-306217b3f999?w=500',
    ],
    category: 'electronics',
    rating: 4.8,
    reviewsCount: 892,
    inStock: true,
    brand: 'Apple',
    colors: ['Titane naturel', 'Titane bleu', 'Titane noir'],
    tags: ['smartphone', 'premium', '5g'],
  },
  {
    id: '3',
    name: 'Levi\'s 501 Original',
    description: 'Le jean iconique Levi\'s 501, coupe droite classique en denim de qualité.',
    price: 89.99,
    images: [
      'https://images.unsplash.com/photo-1542272604-787c3835535d?w=500',
    ],
    category: 'clothing',
    rating: 4.6,
    reviewsCount: 543,
    inStock: true,
    brand: 'Levi\'s',
    sizes: ['28', '30', '32', '34', '36'],
    colors: ['Bleu délavé', 'Noir', 'Brut'],
    tags: ['denim', 'casual', 'classique'],
  },
  {
    id: '4',
    name: 'Sony WH-1000XM5',
    description: 'Casque sans fil avec réduction de bruit exceptionnelle et son haute résolution.',
    price: 399.99,
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500',
    ],
    category: 'electronics',
    rating: 4.9,
    reviewsCount: 1205,
    inStock: true,
    brand: 'Sony',
    colors: ['Noir', 'Argent'],
    tags: ['audio', 'noise-cancelling', 'wireless'],
  },
  {
    id: '5',
    name: 'Ray-Ban Wayfarer',
    description: 'Les lunettes de soleil iconiques Ray-Ban Wayfarer, protection UV400.',
    price: 154.00,
    images: [
      'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500',
    ],
    category: 'accessories',
    rating: 4.7,
    reviewsCount: 674,
    inStock: true,
    brand: 'Ray-Ban',
    colors: ['Noir', 'Écaille', 'Transparent'],
    tags: ['sunglasses', 'fashion', 'uv-protection'],
  },
  {
    id: '6',
    name: 'Adidas Ultraboost 22',
    description: 'Chaussures de running avec technologie Boost pour un retour d\'énergie optimal.',
    price: 189.99,
    images: [
      'https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500',
    ],
    category: 'shoes',
    rating: 4.6,
    reviewsCount: 421,
    inStock: true,
    brand: 'Adidas',
    sizes: ['39', '40', '41', '42', '43', '44', '45'],
    colors: ['Blanc', 'Noir', 'Gris'],
    tags: ['running', 'sport', 'boost'],
  },
  {
    id: '7',
    name: 'MacBook Pro 14"',
    description: 'MacBook Pro avec puce M3 Pro, écran Liquid Retina XDR et jusqu\'à 18h d\'autonomie.',
    price: 2499.00,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=500',
    ],
    category: 'electronics',
    rating: 4.9,
    reviewsCount: 756,
    inStock: true,
    brand: 'Apple',
    colors: ['Gris sidéral', 'Argent'],
    tags: ['laptop', 'professional', 'm3'],
  },
  {
    id: '8',
    name: 'The North Face Nuptse',
    description: 'Doudoune emblématique The North Face avec isolation thermique 700.',
    price: 329.00,
    images: [
      'https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500',
    ],
    category: 'clothing',
    rating: 4.8,
    reviewsCount: 892,
    inStock: true,
    brand: 'The North Face',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: ['Noir', 'Bleu', 'Rouge'],
    tags: ['winter', 'outdoor', 'warm'],
  },
];